// packages/extension-content-ui/src/components/sign-in/sign-in.tsx
import { Component, Event, EventEmitter, h, Host } from '@stencil/core';

@Component({
  tag: 'vocably-sign-in',
  styleUrl: 'sign-in.scss',
  shadow: true,
})
export class VocablySignIn {
  @Event() confirm: EventEmitter;

  render() {
    return (
      <Host data-test="sign-in">
        <div class="p">Please sign in to proceed.</div>
        <div class="p">
          <button
            class="button"
            data-test="sign-in-button"
            onClick={() => this.confirm.emit()}
          >
            Sign in or Create an account
          </button>
        </div>
        <div>
          By signing in, you agree to our{' '}
          <a
            class="link"
            href="https://vocably.pro/terms-and-conditions.html"
            target="_blank"
          >
            Terms of Service
          </a>{' '}
          and{' '}
          <a
            class="link"
            href="https://vocably.pro/privacy-policy.html"
            target="_blank"
          >
            Privacy Policy
          </a>
          .
        </div>
      </Host>
    );
  }
}

// packages/app/src/app/auth/sign-in/sign-in.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
})
export class SignInComponent implements OnInit {
  constructor(public auth: AuthService) {}

  ngOnInit(): void {}
}

<button class="button block mb-1" (click)="auth.signIn()">
  <app-google-icon class="middle mr-0_5"></app-google-icon>
  Sign in with Google
</button>
<div class="text-center">
  By signing in, you agree to our
  <a href="/page/terms-and-conditions" target="_blank">Terms and Conditions</a>
  and <a href="/page/privacy-policy" target="_blank">Privacy Policy</a>.
</div>
